### ISSUE TITLE
Need faucet for testing

### ISSUE THREAD

**Issue by bajian** [eth-classic/mordor#15]
Anyone give me some faucet,please. Thank you!
0x81053FbafbbA98a7288D898760c712351D19CF0c

The following facet canot be open:
Mordor faucet: http://mordor.canhaz.net/, http://mordor.etherdrip.net/
It is inconvenient for the beginners to mine it.

**Comment by q9f** [comment]
```shell
geth --mordor account new
geth --mordor --mine --miner.threads 1
```
