### ISSUE TITLE
Need Mordor test faucet

### ISSUE THREAD

**Issue by patidarmanoj10** [eth-classic/mordor#6]
Can you please let us know where can get Mordor test faucet?

**Comment by soc1c** [comment]
Mine it. Mordor is permissionless. :)

**Comment by patidarmanoj10** [comment]
I know I can mine. I was wondering if I could get it ready.

**Comment by soc1c** [comment]
Oh sorry, I was misunderstanding the question.

You can use `puppeth` social faucet included in Multi-Geth.
